[FEAT] Implement heredoc expansion but not support all corner cases yet
LeaYeh/minishell pull request #150
Opened 2024-02-03 19:01 UTC by LeaYeh

* heredoc content has different expansion rules than normal command line arguments, so we need new mask for heredoc content.

2024-02-03 19:01 UTC, LeaYeh commented
Resolves #65

2024-02-04 01:51 UTC, itislu requested changes

2024-02-04 01:51 UTC, itislu commented on source/backend/redirection/heredoc.c
> +		if (!append_line_to_file(line, filename))
How about converting the `line_list` at the start of `handle_heredoc_content()` to a string?
And then, just expand that one string and write to the heredoc tmp-file just once instead of for every line?

This would also fix the incorrect error message for bad substitution inside of a heredoc content.

2024-02-05 12:43 UTC, itislu commented
* Once #153 is merged into this branch, we can rebase and merge to main.

2024-02-06 13:31 UTC, itislu approved these changes

2024-02-06 13:37 UTC, merged