[FEAT] Parser - parsing the syntax by the grammar
LeaYeh/minishell pull request #16
Opened 2023-12-20 17:23 UTC by LeaYeh

2023-12-20 19:40 UTC, itislu requested changes

2023-12-20 19:40 UTC, itislu commented on libraries/libft/build/libft.mk
> +#   Stack:
@itislu Move to appropriate place (alphabetically)

2023-12-20 19:53 UTC, itislu requested changes

2023-12-20 19:53 UTC, itislu commented on source/frontend/parser/parse.c
> +			return (false);
pt_entry needs to be freed in all return cases.

2023-12-20 19:53 UTC, itislu commented on source/frontend/parser/parse.c
> +			ft_dprintf(2, "%s: syntax error near unexpected token `%s'\n",
If malloc in get_next_pt_entry() fails, parse() will report a syntax error.

2023-12-20 19:56 UTC, itislu requested changes

2023-12-20 19:56 UTC, itislu commented on source/frontend/parser/parser_operation.c
> +		return (false);
If ft_stknew fails, free tmp.

2023-12-20 20:03 UTC, itislu requested changes

2023-12-20 20:03 UTC, itislu commented on source/frontend/parser/parser_operation.c
> +		return (false);
If push_token fails, reduction_node has to be freed.

2023-12-20 20:17 UTC, itislu requested changes

2023-12-20 20:17 UTC, itislu commented on source/frontend/parser/parsing_table.c
> +	if ((action_mask & A_ACCEPT) == A_ACCEPT && \
I think just action_mask == A_ACCEPT is better to understand the meaning here.

2023-12-20 20:17 UTC, itislu commented on source/frontend/parser/parsing_table.c
> +	i = -1;
Initializing to -1 is not necessary anymore, there are enough lines available.
I would say init with 0 is better since in this case there is no consistency to keep up with.

2023-12-20 21:06 UTC, itislu requested changes

2023-12-20 21:11 UTC, itislu commented on source/frontend/parser/parse.c
> +			ft_dprintf(2, "%s: syntax error near unexpected token `%s'\n",
This issue will stay open for now.
We discussed if malloc fails anywhere, maybe we should have a clean_and_exit_shell function and let shell be a global variable.
We still need to think about it and wait for more modules.

2023-12-21 12:05 UTC, LeaYeh commented on source/frontend/parser/parser_utils.c
> +	*parse_stack = NULL;
done

2023-12-21 13:27 UTC, itislu approved these changes

2023-12-21 13:27 UTC, merged