[FIX] Fix norm issues under utils folder
LeaYeh/minishell pull request #185
Opened 2024-02-17 16:20 UTC by LeaYeh

2024-02-17 16:23 UTC, LeaYeh commented
The regression test failed is randomly happen not related to this PR

2024-02-18 08:19 UTC, LeaYeh commented
@itislu After fix all norm issue I will fine-tune the header file structure

2024-02-18 13:52 UTC, itislu requested changes

2024-02-18 13:52 UTC, itislu commented on include/utils.h
> -void		print_token_list(t_list *token_list);
I think it should be moved to debug.h instead of deleted, no?

2024-02-18 13:52 UTC, itislu commented on source/utils/stack_status_utils.c
> +void	print_parse_stack(t_list *node)
This function should also be moved to print_stack.c, since `print_state_stack()` was also moved there.

2024-02-18 13:52 UTC, itislu commented on source/utils/stack_status_utils.c
> +t_ast	*get_ast_from_stack(t_list *node)
This function could be moved back to stack_utils.c then. Or, if you'd prefer to separate the ast, rename this file to ast_utils.c.

2024-02-18 13:52 UTC, itislu commented on source/debug/show_list.c
> +void	print_token_list(t_list *token_list)
`print_token_list()` and `print_token()` can replace `ft_show_token_list()` and `ft_print_token()`.
Then show_list.c could also be renamed to print_list.c

2024-02-18 14:57 UTC, LeaYeh commented on include/utils.h
> -void		print_token_list(t_list *token_list);
Now the pr is only about the norm issue , i will reorganize the headers in another pr

2024-02-18 14:59 UTC, LeaYeh commented
Let us leave the header structure in another pr

2024-02-18 16:46 UTC, itislu commented
Okay. Would you like to fix the other 3 comments?

2024-02-18 16:48 UTC, LeaYeh commented
No, bc i want to change all header files

2024-02-18 17:00 UTC, itislu approved these changes

2024-02-18 17:00 UTC, merged