[FIX] Fix newline after program with exit code 130
LeaYeh/minishell pull request #386
Opened 2024-11-14 23:32 UTC by itislu

- [ ] First merge #354 

---

- Fixes programs with exit code 130 causing a newline.
- Fixes minishell running in minishell printing too many newlines after SIGINT + exit.
- Fixes nested subshells printing too many newlines: `( ( (cat) ) )`
- Fixes `cat | ./segfault` behavior: `Segmentation fault` only gets printed at end of pipeline.
- This also fixes the exit code affecting `&&`/`|| `: `./return_130 || echo 123` did not print `123`.

- Resolves #257

---

### Known issues

- `(sleep 3 && ./segfault)` should not print `Segmentation fault` (which is super weird bc `(./segfault)` **does** print `Segmentation fault`!
- SIGQUIT behavior in subshells remains unsolved - #206

2024-11-15 00:20 UTC, itislu commented
Something is wrong with the CI shell scripts...

2024-11-16 07:05 UTC, LeaYeh reviewed
Maybe need to check tomorrow

2024-11-16 07:05 UTC, LeaYeh commented on source/backend/executor/wait_process.c
>  	bool	got_sigint;
Hey I just noticed this var, can we change the got?

2024-11-16 07:05 UTC, LeaYeh commented on source/backend/executor/wait_process.c
> +static int	wait_child_pid(pid_t pid, bool *got_sigint)
What make this different than before

2024-11-16 07:05 UTC, LeaYeh approved these changes

2024-11-16 07:06 UTC, LeaYeh requested changes
I don't see the difference need explanation

2024-11-16 07:11 UTC, LeaYeh commented
And I feel sometimes you over norminattee make the code confusing me.
For example, is the wait child pid and different than wait pid? Why need a sub function to take the function jump but not gain any benefit?

2024-11-16 08:14 UTC, itislu commented
I'm happy to do a code review on campus whenever you have time!

2024-11-19 21:37 UTC, LeaYeh approved these changes

2024-11-19 21:37 UTC, merged