[FEAT] Implement heredoc without handle process
LeaYeh/minishell pull request #55
Opened 2023-12-30 19:34 UTC by LeaYeh

2023-12-31 00:48 UTC, itislu commented
The Github Action works now, including a diff of the results.

2023-12-31 08:43 UTC, LeaYeh commented
I should not merge main branch into it, I will rebase and force update tomorrow

2023-12-31 08:53 UTC, itislu commented
I merged the gh-actions branch into this branch already, that's why there are no changes from merging main.
If you prefer, you can revert the merge from main and it will look okay on the history graph, I think.

2023-12-31 09:26 UTC, LeaYeh commented
I already merged the gh-actions branch into main, need to rebase and force push this branch again

2024-01-01 09:47 UTC, itislu requested changes

2024-01-01 09:47 UTC, itislu commented on source/utils/file_utils.c
> +	sprintf(filename, "/tmp/%s_%s_%d-%d",
For code safety, we should use snprintf. sprintf does not check if the expanded string is longer than the buffer.
I will add ft_snprintf to libft today.

2024-01-01 09:47 UTC, itislu commented on source/utils/file_utils.c
> +	unlink(*filename);
We have to check if unlink fails (return value -1).
In such a case, the file does not get deleted, so it's better to then not free the filename string.

2024-01-01 09:47 UTC, itislu commented on source/utils/file_utils.c
> +	fd = open(filename, O_CREAT | O_RDWR | O_APPEND, 0644);
I think I found a perfect solution for the heredoc filename:
There is a flag for open() called `O_TMPFILE` ([manual entry](https://man7.org/linux/man-pages/man2/open.2.html#:~:text=O_TMPFILE%20(since%20Linux%203.11))).
It creates an **unnamed** file in the directory specified as an argument.
We just need to close the file descriptor later, because closing the fd will delete the file.

2024-01-01 09:47 UTC, itislu commented on source/utils/file_utils.c
> +	fd = open(filename, O_CREAT | O_RDWR | O_APPEND, 0644);
Also, there are [system macros](https://jameshfisher.com/2017/02/24/what-is-mode_t/) for the `mode_t` argument of open().
0644 would be: 
```C
S_IWUSR | S_IRGRP | S_IROTH
```

2024-01-01 09:47 UTC, itislu commented on source/utils/file_utils.c
> +	close(fd);
close() can actually fail too (return value -1).

Manual:
>        The close() function shall fail if:
> 
>        EBADF  The fildes argument is not a open file descriptor.
> 
>        EINTR  The close() function was interrupted by a signal.
> 
>        The close() function may fail if:
> 
>        EIO    An I/O error occurred while reading from or writing to the file system.
>

2024-01-01 09:47 UTC, itislu commented on source/backend/redirection/heredoc.c
> +	ft_free_and_null((void **)&line);
`free()` would be enough (if you disagree and find it annoying that I always point this specifically out, please tell me).

2024-01-01 13:29 UTC, LeaYeh commented on source/utils/file_utils.c
> +	fd = open(filename, O_CREAT | O_RDWR | O_APPEND, 0644);
It's hard to handle the fds from heredoc which need to be open and held in the parent process.
TODO: We could check it after the first version

2024-01-01 13:52 UTC, itislu approved these changes

2024-01-01 13:56 UTC, merged

2024-03-20 01:40 UTC, itislu commented on source/utils/file_utils.c
> +	fd = open(filename, O_CREAT | O_RDWR | O_APPEND, 0644);
Update: TMPFILEs are not supported on every filesystem. The one on the school computors is apparently not one of them.