[FEAT] Parameter expansion
LeaYeh/minishell pull request #60
Opened 2024-01-01 15:10 UTC by itislu

#### Parameter expansion handles the following cases:
| Input | Expanded |
|--------|--------|
| `$USER` | `<username>` |
| `${USER}` | `<username>` |
| `$?` | `<exit code>` |
| `$` | `$` |
| `$abc` | `<empty string>` | 
| `$abc$USER` | `<username>` |
| `$"USER"` | `<username>` |
| `$'USER'` | `USER` |
| `${USER?abc}` | `<username>` |
| `${??abc}` | `<exit code>` | 
| `${??$USER}` | `<exit code>` |
| `"$USER"` | `"<username>"` |
| `'$USER'` | `$USER` |
| `$"$USER"` | `<username>` |
| `$'$USER'` | `'$USER'` | 
| `"'$USER'"` | `'<username>'` |

#### Quote removal is not yet implemented and will follow in another feature.

#### There are still open questions to resolve:
- [ ] `echo ${abc.$USER`
 		At the moment it will just leave the string as is.
- [ ] Where to handle the "%s: bad substitution" error message, e.g. `${abc.}`?
- [ ]  This test case is terrible, bc it changes the command table:
bash-5.1$ $abc 123
bash: 123: command not found

2024-01-01 16:36 UTC, itislu commented on source/utils/string_utils.c
> +	}
Need to reduce indentation.

2024-01-01 16:36 UTC, itislu commented on source/debug/print_expanded_cmd_table.c
> +			if (!expand_cmd_table(cmd_table, shell))
Should not modify the command table

2024-01-01 17:06 UTC, LeaYeh commented
Known issue that will effect the interface, need to be solved

```sh
bash-5.1$ ${} && echo 1
bash: ${}: bad substitution
bash-5.1$ ${} || echo 1
bash: ${}: bad substitution
bash-5.1$ ${} | echo 1
1
bash: ${}: bad substitution
```

2024-01-01 17:14 UTC, LeaYeh requested changes
Known issues that will effect the interface, need to be solved

```sh
bash-5.1$ ${} && echo 1
bash: ${}: bad substitution
bash-5.1$ ${} || echo 1
bash: ${}: bad substitution
bash-5.1$ ${} | echo 1
1
bash: ${}: bad substitution
```

```sh
bash-5.1$ $aaaaa || echo 1
bash-5.1$ $aaaaa && echo 1
1
```

```sh
bash-5.1$ "$abc"
bash: : command not found
```

Before we figure out these issues we can't decide the interface.

2024-01-01 17:41 UTC, LeaYeh commented
Maybe the expander could return...
1. list == NULL
    * executor should execute `true` as command, means do nothing and exit==0
2. list->content == NULL
    *  executor will use the first non-null content as command name and others are command args
    * empty string has different meaning with NULL

2024-01-01 18:01 UTC, itislu commented
Expansion happens during the executor. 
Proof:
```sh
bash-5.1$ echo 1 && echo ${a.b} || echo 1
1
bash: ${a.b}: bad substitution
```

2024-01-01 18:53 UTC, itislu commented
Executor needs to filter out all `node->content == NULL` nodes and remove them from the list.
```sh
bash-5.1$ echo $aaa 1
1
```

2024-01-01 19:06 UTC, itislu commented
How NULL should behave for redirections:
```sh
bash-5.1$ echo 1 > abc > $aaa > def
bash: $aaa: ambiguous redirect
bash-5.1$ ls
abc
bash-5.1$ cat abc
```
```sh
bash-5.1$ echo 1 > abc > $USER > def
bash-5.1$ ls
abc  def  ldulling
bash-5.1$ cat def
1
```

2024-01-01 22:20 UTC, itislu commented
#### Solution for the `bad substitution` problem:

If the expander encounters a bad substitution, it should return `false`, but also set the string it got to `NULL`.
The executor then can check the following:
- If the expander returns `false` and the string got turned to `NULL`, an expander error like `bad substitution` happened.
  The executor should do nothing else for the current command table anymore, and go to the next command table.

- Otherwise, if the expander returns `false` and the string got NOT turned to `NULL`, a critical issue occured, like a malloc fail, and the shell needs to exit.

2024-01-03 14:05 UTC, itislu commented on include/expander.h
> +
@LeaYeh What do you think, are these defines ok here?

2024-01-03 14:08 UTC, itislu commented on source/debug/print_expanded_cmd_table.c
> +			if (!expand_cmd_table(cmd_table, shell))
@LeaYeh Please help me where we should put the expander test function for the moment.

2024-01-03 15:17 UTC, LeaYeh commented on source/debug/print_expanded_cmd_table.c
> +			if (!expand_cmd_table(cmd_table, shell))
Modify to the static function

2024-01-03 18:06 UTC, LeaYeh commented
The interface of expander...
- if true...
  1. string=string, *list = one element list (except wildcard)
- if false...
  1. general error, string=NULL, *list = NULL
  2. expander error, string=string, *list = NULL

TODO list for executor...
1. after expander if cmd_name => NULL, the cmd_name should be replace by the first non-null argument
2. cmd_args need to filter out the NULL
=> Maybe combine the cmd_name and cmd_args into one list in a function and pass to expander 1-1 then separate back
3. if the executor receives "1 2 3" as cmd_name, it should be split into "1" "2" "3"

2024-01-03 18:21 UTC, LeaYeh commented on include/expander.h
> +
use enum

2024-01-03 18:27 UTC, LeaYeh commented
Need to be checked...
Should we handle the different expansions by the scenario in expander or just in executor?
* in heredoc, the quotes will be removed but not expand

2024-01-03 18:34 UTC, itislu commented
- [ ] Need to provide the submodules of the expander as separate interfaces for the executor.

2024-01-06 13:26 UTC, LeaYeh requested changes

2024-01-06 13:26 UTC, LeaYeh commented on source/frontend/expander/expander_utils.c
> +	is_open_pair('"', RESET);
Maybe reset the whole sets may be more clear

2024-01-06 13:30 UTC, LeaYeh approved these changes

2024-01-06 15:14 UTC, merged