[FEAT] Implement core process flow for execution
LeaYeh/minishell pull request #80
Opened 2024-01-12 22:17 UTC by LeaYeh

1. Handle AND, OR, PIPE and subshell operation in general way
    2. Make sure subshell and pipeline could get individule working env
    3. Wait for exit code with the correct command table
    4. Add final command table for execution
    5. Handle external and builtin command behavior
    6. Propagate general error through the whole process and exit minishell

2024-01-14 14:02 UTC, itislu requested changes

2024-01-14 14:02 UTC, itislu commented on source/backend/executor/executor_utils.c
> +	while (all_path && all_path[i])
`all_path` already get's checked for `NULL` before and doesn't need to be checked for every iteration of the while loop.

2024-01-14 18:16 UTC, itislu requested changes

2024-01-14 18:58 UTC, itislu requested changes

2024-01-14 18:58 UTC, itislu commented on source/backend/executor/handle_simple_cmd.c
> +		ft_clean_and_exit_shell(shell, shell->exit_code, NULL);
`final_cmd_table` does not get free'd

2024-01-14 23:32 UTC, LeaYeh commented
Now I truly believe something going wrong

2024-01-14 23:53 UTC, itislu commented
Yuup, we should run the tester locally with this branch and monitor the system.

2024-01-15 13:44 UTC, itislu approved these changes

2024-01-15 15:01 UTC, merged